name: NPM Release
on:
  push:
    tags:
      - "@zwoo/api-zrp@v*"

jobs:
  zrp:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/@zwoo/api-zrp@v')
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        working-directory: zrp/api-zrp
      - run: npm publish --provenance --access public
        working-directory: zrp/api-zrp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_KEY }}
