name: Nuget Release
on:
  push:
    tags:
      - "Zwoo.Api.ZRP@v*"
jobs:
  zrp:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/Zwoo.Api.ZRP@v*')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"
      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/Zwoo\.Api\.ZRP\@v/}" >> $GITHUB_ENV
      - name: Log version
        run: echo ${VERSION}
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Pack
        working-directory: zrp/Zwoo.Api.ZRP
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        working-directory: zrp/Zwoo.Api.ZRP
        run: dotnet nuget push ZWoo.Api.ZRP.${VERSION}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
